---
- name: Ensure Apache is installed.
  yum:
    name: "{{ item }}"
    state: installed
    enablerepo: "{{ apache_enablerepo }}"
  with_items: apache_packages

- name: Ensure Apache is started and enabled on boot.
  service: 
    name: "{{apache_daemon }}"
    state: started
    enabled: yes
