---
- name: Set clock
  template: >
    src=clock.j2
    dest=/etc/sysconfig/clock
    owner=root
    group=root
    mode=0644

- name: Set zoneinfo
  file: >
    src=/usr/share/zoneinfo/{{ timezone }}
    dest=/etc/localtime
    state=link
    force=yes
